### ISSUE TITLE
Any chance to have silicon native App on Mac ?

### ISSUE THREAD

**Issue by OLH21** [braden-w/whispering#106]
@braden-w will it be possible to have a native ARM app or not ? 
Your app is simply the best solution for system wide STT on mac and it might be usefull to think of an ARM solution because at some point apple will drop Intel support

**Comment by braden-w** [comment]
Thank you so much @OLH21 ! Hopefully my releases will start including support for native ARM. I'm still testing out the CI/CD in the Actions tab, but once they start working consistently there will be support!

**Comment by braden-w** [comment]
Hey @OLH21, thank you and really appreciate the kind words!

I finally got releases working again and there should be an ARM app in the latest release (as of writing, `v4.2.1`).

https://github.com/braden-w/whispering/releases

Could you take a look and reopen this thread if you still have issues? Thank you so much once again!

**Comment by OLH21** [comment]
Thanks that's a gret new but https://github.com/braden-w/whispering/issues/115 :(
