### ISSUE TITLE
Desktop ver. prompts to verify API key

### ISSUE THREAD

**Issue by Silverlinin** [braden-w/whispering#107]
Even though the API key has already been created, I have tried generating another one. 

"Something went wrong. Please verify that your [API Key in settings](https://tauri.localhost/key) is correct."

**Comment by braden-w** [comment]
Hey @Silverlinin , could you give me more details on reproduction in [the latest version](https://github.com/braden-w/whispering/releases/tag/v4.2.1)? I noticed that the hyperlink for the API Key in settings points to `https://tauri.localhost/key`, which is quite strange.
