### ISSUE TITLE
Add GROQ api

### ISSUE THREAD

**Issue by OLH21** [braden-w/whispering#110]
Would be nice to have the new and very fast Groq api also in the app and extension. Would be nice to offer a choice alternative from OpenAi.

**Comment by kerfern** [comment]
second this suggestion. it is faster than openai.

**Comment by AlpSantoGlobalMomentumLLC** [comment]
I like that one!  ❤️

**Comment by AlpSantoGlobalMomentumLLC** [comment]
If you're still search a Groq version,  here it's a Groq only fork. 
 Because patience is not my strength. ;)
[]( https://github.com/AlpSantoGlobalMomentumLLC/whisperingGroq/tree/main)
 
PS:  I will stop the fork  if braden-w, maybe implement the Groq support by his own...

**Comment by braden-w** [comment]
Closed in #236 !

Latest version has Groq support, just go to Settings/Transcriptions. Thank you @AlpSantoGlobalMomentumLLC  and @OLH21 for the inspiration!
