### ISSUE TITLE
Using Whispering to dictate in multiple languages in my work as a patent translator

### ISSUE THREAD

**Issue by michaelbeijer** [braden-w/whispering#111]
Hi Braden,

Thanks so much for this amazing tool, which is super handy in my work as a Dutch-English patent translator. It allows me to easily switch back and forth between Dutch and English dictation. Something like this was totally impossible only a few years ago when I was still struggling with Dragon Naturally Speaking. 

I usually use Talon, for English dictation and voice commands, but have recently switched to using Whispering for Dutch and English dictation, and Talon for commands.

I've also written a quick post about Whispering over on LinkedIn so fellow translators become aware of it as well: https://www.linkedin.com/posts/michaelbeijer_%3F%3F%3F%3F%3F-%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F-%3F%3F%3F-activity-7210317838350233600-vMZa?utm_source=share&utm_medium=member_desktop

Michael

**Comment by OLH21** [comment]
I think you just lost this auto switch language ability in V4 ;) as state in this issue #116

**Comment by braden-w** [comment]
Hey everyone, thank you for bringing this to my attention!

@OLH21 as of writing, #125 was merged and now closes #116. Thank you again, everyone—would not have made this feature without this issue!

**Comment by braden-w** [comment]
Also @michaelbeijer , thank you so much for the shoutout! Really appreciate it :)

> I've also written a quick post about Whispering over on LinkedIn so fellow translators become aware of it as well: https://www.linkedin.com/posts/michaelbeijer_%3F%3F%3F%3F%3F-%3F%3F%3F%3F%3F%3F%3F%3F%3F%3F-%3F%3F%3F-activity-7210317838350233600-vMZa?utm_source=share&utm_medium=member_desktop
