### ISSUE TITLE
ARM version not working On Mac M1

### ISSUE THREAD

**Issue by OLH21** [braden-w/whispering#115]
X86 is ok with right click open and Rosetta insdtalled but the ARM files does not execute , says it is damaged even with right click open . anyone else with the same issue ?

**Comment by doxgt** [comment]
Can folks please inform us here whether the app version is working on Mac M1, perhaps in the coming days? That way I can let family members who use MacBooks know.  It saves me from having to test it at their places.

In addition, we can assume that the web interface, https://whispering.bradenwong.com, works on Safari the same way it works on other browsers on Windows?

**Comment by rkhrkh** [comment]
_X86 is ok with right click open .... but the ARM files does not execute , says it is damaged even with right click open_

Exactly the same issue here on my MacBook M1 Pro.

**Comment by OLH21** [comment]
Still not working on the 4.21 new version ... ( right click and open still return an error)

**Comment by braden-w** [comment]
Hey guys, sorry for the delayed response!


> In addition, we can assume that the web interface, https://whispering.bradenwong.com, works on Safari the same way it works on other browsers on Windows?

@doxgt  yes, we can assume that the web interface should work on Safari similarly on other Operating Systems. Can confirm it works on chrome and safari on MacOS, and although unfortunately I don't have a Windows laptop to test it, browser APIs are stable—it's desktop APIs that are dangerous. Thank you for watching.

**Comment by braden-w** [comment]
Unfortunately, I don't have an Apple Silicon Mac yet, but could you guys send me the exact error message that you're getting and more steps for reproduction?

It seems like the key word is "damaged." I've been looking online and some extra keywords to know what to search for would be very helpful!

**Comment by rkhrkh** [comment]
I downloaded Whispering version 4.5.1 (aarch64.dmg).

After downloading, I navigated to the Applications folder and right-clicked on Whispering. Upon doing so, a message appeared: 

_'“Whispering” is damaged and can’t be opened. You should move it to the Bin.'_

 The options presented were "Move to Bin" on the left button and "Cancel" on the right button. I selected "Cancel."

I then right-clicked to open the app again from the Applications folder.

Normally, there would now be **a new option** to open the app despite the warning.

However, I still only have the options "Move to Bin" or "Cancel."

**Comment by kerfern** [comment]
confirm that i have the same issue. as described by @rkhrkh

**Comment by rkhrkh** [comment]
Whispering_4.5.2_aarch64.dmg

 the same issue

**Comment by rkhrkh** [comment]
Whispering_4.5.3_aarch64.dmg

the same issue

**Comment by OLH21** [comment]
Problem is the way apple handle unauthorised app is the same as the damaged files one with the same message . But normally you can open unsigned app with right click open. So it might be a real problem with the ARM version.

**Comment by redffish** [comment]
Whispering_4.6.1_aarch64.dmg

Same issue. Right click open doesn't help
 
![image](https://github.com/braden-w/whispering/assets/54925755/b3b21626-64c9-482e-9ed2-1fb032676ea4)

**Comment by kerfern** [comment]
thanks so much @braden-w !
