### ISSUE TITLE
Auto Multi Lingual support lost in V4

### ISSUE THREAD

**Issue by OLH21** [braden-w/whispering#116]
The old version has the auto detect language feature by default, but now you have to specify your output language , wich could be great or very bad depending on who is using the app. I personnaly work in several language and I found very usefull not to have to switch language and have Whisper detect the actual spoken language

**Comment by michaelbeijer** [comment]
Oh crap, same here. If this is true, can you **please** make it so this is optional somehow? Translators, such as myself, find this a very useful feature. For example, I use it to dictate in Dutch and English all day long, and would hate to have to keep changing the language back and forth. This would make it pretty much unusable for me, sadly.

**Comment by braden-w** [comment]
I'm on it right now! Sorry again for the delay and sudden breakage, have been triaging tasks. Will get a release later today that addresses this!

**Comment by braden-w** [comment]
![CleanShot 2024-06-29 at 12 35 43](https://github.com/braden-w/whispering/assets/13159333/ad0746b6-7267-4e70-85d1-33b2ea91dd6a)

Now working in #125 ! Going to get a deployment of that up soon.

**Comment by michaelbeijer** [comment]
Wow, thanks so much for this!

**Comment by braden-w** [comment]
Of course!! Please feel free to reopen this thread if the issue persists.

Thank you all again for the support!
