### ISSUE TITLE
Update Breaks Google sheets

### ISSUE THREAD

**Issue by Dhubbs** [braden-w/whispering#118]
Hey, Loved the product and have been using it for a while however this newest update has caused me to many issues and I had to unistall. Seems like it is placing a textbox over other textboxes? Works a little wonky on some pages but a major spot that it causes issues is on google sheets. Breaks the functionality to edit cells.

**Comment by OLH21** [comment]
You can just activate it on choosen website , instead of all web site in the extension setting

**Comment by braden-w** [comment]
Disabled extension for the bing website and all other websites except ChatGPT and Anthropic in https://github.com/braden-w/whispering/pull/124 .

Extension is waiting for approval as we speak! Hope this helps. In the meantime, please feel free to disable the extension 🙏 I apologize again for the breakage
