### ISSUE TITLE
Missing Windows executable in release assets

### ISSUE THREAD

**Issue by suntube** [braden-w/whispering#119]
I'm trying to download the latest version of Whispering for Windows, but I can't find a Windows executable in the release assets.

![chrome_PuQcZx0aoQ](https://github.com/braden-w/whispering/assets/14271594/5b7b2ec7-cd8b-4369-beae-968a361d2d0f)

**Comment by michaelbeijer** [comment]
I was just wondering the same thing here.

**Comment by braden-w** [comment]
Hey everyone, seems like there was a mistake with the GitHub actions and I'm working on it! I haven't published the release because despite the 4.0.0 release there are still random small bugs I am squashing 😅

**Comment by swimJim** [comment]
Thank you for your hard work.

**Comment by braden-w** [comment]
Thank you guys again!

The latest version will incorporate the Windows package. The issue was than env variables that was fixed using `cross-env` in [this commit](https://github.com/braden-w/whispering/commit/f78abf8b68b82d0194bf858abe81c33b16491e1f).

**Comment by suntube** [comment]
Thank you for your kind attention, I really appreciate your work!

**Comment by braden-w** [comment]
No problem! Hopefully the release builds and comes out today!

**Comment by braden-w** [comment]
Got the build working, can you guys test if the Windows executable works in the latest release?

https://github.com/braden-w/whispering/releases/tag/v4.2.1

Thank you guys once again!
