### ISSUE TITLE
"Oops, an error occurred!" When uploading an image on chatGPT

### ISSUE THREAD

**Issue by suntube** [braden-w/whispering#120]
Hello there. I want to make a report. Whenever I try to post an image in chat GPT, I always face this error. When I disabled the extension, it works fine. But when I re-enable the extension, again I keep facing the same issue.

![chrome_AncFOn3sJ0](https://github.com/braden-w/whispering/assets/14271594/eac7068b-d3fa-4f7b-a1ae-59bba1c3ccde)

**Comment by TheMoaniestPunk** [comment]
Seconded—It started happening after the Whispering update the other day. Whispering (chromium plugin) has become a massive part of my workflow, but I've had to disable it, too.

Please do fix it if you can :) 

Also, I hate to say it, but I find the microphone widget incredibly annoying. Is there any way to disable it?

Many thanks

**Comment by braden-w** [comment]
Will take a look at this today! Sorry for the bugs. I will also add a feature to disable the microphone widget

**Comment by TheMoaniestPunk** [comment]
Hi Braden, 

> "Oops, an error occurred!" When uploading an image on chatGPT

This bug persists. Again, it applies to images as well as to any upload or pasting into GPT.

Is this because the changes are still waiting for approval?
