### ISSUE TITLE
Messing up UI for Bing

### ISSUE THREAD

**Issue by vassovass** [braden-w/whispering#121]
Extension is breaking my BIng UI - as you can see I have a few other extensions so it might be possible that its another extension confliction with yours, but I dont hink so.

![image](https://github.com/braden-w/whispering/assets/19572518/cbb55f65-38ea-4a88-930e-03d943cb37bf)

**Comment by braden-w** [comment]
Will take a look at this! I didn't mean to release the extension this early and am working to fix up the content script for the microphone

**Comment by braden-w** [comment]
Disabled extension for the bing website and all other websites except ChatGPT and Anthropic in #124 . 

Extension is waiting for approval as we speak! Hope this helps.

**Comment by braden-w** [comment]
In the meantime, please feel free to disable the extension 🙏 I apologize again for the breakage
