### ISSUE TITLE
Critical Paste Function Inoperable in x86 Version on MacBook M1 Pro

### ISSUE THREAD

**Issue by rkhrkh** [braden-w/whispering#122]
The ARM Vision version is incompatible with the MacBook M1 Pro, necessitating the download of the x86 version. Although the crucial _"Paste contents from clipboard after successful transcription"_ function is present in this version, it fails to operate as intended. Despite attempts to activate the feature, it remains non-functional. 

Given that this is the application's most essential capability, I was compelled to uninstall the current version and revert to the previous one.

**Comment by braden-w** [comment]
Hey @rkhrkh , sorry to hear that. Could you verify that this problem still exists in the [latest version](https://github.com/braden-w/whispering/releases)? I've made a few pull requests that have attempted to address this issue, such as #148 , #132 .

Also, make sure that Whispering has access to the accessibility settings, which you should be prompted for in the latest version.

Hope this helps! If you still have issues, please reopen this issue. Thank you!
