### ISSUE TITLE
Whispering not working on Paymo app field

### ISSUE THREAD

**Issue by xguntis** [braden-w/whispering#123]
Here is the video with the problem https://vimeo.com/971408619/6434ecf20a?share=copy
https://app.paymoapp.com/
Windows 11, Latest chrome browser

Regards,
Guntis

**Comment by braden-w** [comment]
Disabled extension for the bing website and all other websites except ChatGPT and Anthropic in #124 . 

Extension is waiting for approval as we speak! Hope this helps and paymo app works soon after. In the meantime, feel free to disable the extension 🙏
