### ISSUE TITLE
Whispering_4.4.0 Critical Paste Function now working in x86 Version on MacBook M1 Pro

### ISSUE THREAD

**Issue by rkhrkh** [braden-w/whispering#135]
Whispering_4.3.0  and 4.4.0 - The ARM Vision version is incompatible with the MacBook M1 Pro, necessitating the download of the x86 version. Although the crucial _"Paste contents from clipboard after successful transcription"_ function is present in this version, it fails to operate as intended. Despite attempts to activate the feature, it remains non-functional.

Whispering_4.3.0   - A notification appears:

_Please enable accessibility to paste transcription in macOS!
You can enable Whispering in System Preferences > Privacy & Security > Accessibility._

it remains unclear which accessibility permissions should be granted. Despite several attempts,   the crucial _"Paste contents from clipboard after successful transcription"_ function still does not work.

Edit - This issue is resolved in version 4.4.0, but that version still does not provide the feature. See below.

Edit - Version 4.4.0 is now working after some trial and error. See below.

**Comment by rkhrkh** [comment]
The missing feature _"Paste contents from clipboard after successful transcription"_ has caused another problem. Since I use Whispering around the clock every day, I uninstalled the non-functional version 4.3.0 and reinstalled the functioning version 3.4.0. However, after this process, the feature in the older version 3.4.0.  no longer works either, even though the feature is activated:

_Paste contents from clipboard after successful transcription (experimental)_

**Comment by rkhrkh** [comment]
Even version 4.4.0 does not improve the situation. The corresponding notification now directs me to _"Accessibility -> allow the application below to control your computer"_ but even when I enable Whispering there, the feature _"Paste contents from clipboard after successful transcription"_  still does not work. 

After uninstalling version 4.4.0 and reinstalling version 3.4.0, the feature remains non-functional.

**Comment by braden-w** [comment]
Hey @rkhrkh , thank you so much for the detailed logging of this issue and the updates! Coincidentally, I also was having issues with copying and pasting, and my fix was the exact same 😅 I was quiet for the past day as I was trying to debug it. I was going to push an update and a PSA out later today, but you beat me to it. I'm going to be creating a persisting issue as just an FYI for future users who might have this issue. Thank you very much once again!
