### ISSUE TITLE
FYI When Paste Not Working: Troubleshooting Guide for macOS Users

### ISSUE THREAD

**Issue by braden-w** [braden-w/whispering#150]
## Issue Description

Some users on macOS may experience issues with the paste functionality not working correctly. This problem may persist even after enabling whispering in accessibility settings.

## Symptoms

- Paste function doesn't work as expected
- A toast notification appears, suggesting to enable Whispering in accessibility settings
- The issue persists even after enabling Whispering in accessibility

## Solution

https://github.com/braden-w/whispering/assets/13159333/24f0cc91-28c8-4ced-bc08-a20c78dd5652

If you're still experiencing this issue after enabling whispering, follow these steps:

1. Open  Accessibility settings
2. Find the Whispering option
3. Remove Whispering:
   - Click to highlight the Whispering option
   - Press the minus (-) button to remove it
4. Re-add Whispering:
   - Click the plus (+) button
   - Select and add Whispering again
5. Restart the application

These steps have been reported to resolve the issue for affected users, both anecdotally for myself and by [rkhrkh](https://github.com/rkhrkh) in https://github.com/braden-w/whispering/issues/135#issuecomment-2198819538 .

## Additional Notes

- This solution is specific to macOS users
- If you continue to experience issues after trying this solution, please comment on this issue with details about your system configuration and the steps you've taken

This issue will remain open as an ongoing reference for users experiencing this problem. Please feel free to contribute any additional insights or alternative solutions in the comments.

**Comment by rkhrkh** [comment]
"Accessibility -> allow the application below to control your computer" 

In this section of the accessibility settings, you need to activate whispering. There are numerous accessibility settings in macOS, which made it difficult for me to find it at first.

**Comment by braden-w** [comment]
Going to be closing this as it has now been merged into #160 !
