### ISSUE TITLE
Solved - Whispering_4.8.3_aarch64: Visual Indication when running OK now

### ISSUE THREAD

**Issue by rkhrkh** [braden-w/whispering#158]
**Whispering 4.5.2** x64
MacBook Pro M1 with 16 GB RAM

Whispering 4.5.2 now offers the ability to function in the background. However, during dictation with the activated application, there is **no visual confirmation of its active state.** 

Personally, I prefer a visual indicator rather than an auditory one. Due to the absence of a visible activity status indicator during use, I have decided to revert to version 3.4.0.

**Comment by braden-w** [comment]
@rkhrkh is the system tray icon not working or sufficient enough for a status that it is active?

And just to clarify, does that mean that you would prefer for the whole window to come back to the foreground when recording?

**Comment by rkhrkh** [comment]
Whispering_4.5.3_x64.dmg
MacBook Pro M1 with 16 GB RAM

**Issue Identification:** 
The system tray icon is not displayed when working with either of the two external monitors. However, it appears when using the built-in monitor of the MacBook M1 Pro.

**Root Cause:** 
By default, the system tray is only displayed on the primary screen. This becomes problematic as the external monitors are primarily used.

**Impact:** 
When the cursor moves to one of the external monitors, the system tray icon on the MacBook M1 Pro's internal monitor is no longer visible, rendering the application essentially unusable.

**Current Workaround:** 
Reverting to version 3.4.0 of the application.

**Potential User Base Affected:** 
Many users working with external monitors likely face the same issue.

**Proposed Solution:** 
Implement an additional option that allows the application window to remain in the foreground while active, similar to version 3.4.0's functionality. When the application becomes inactive, the window could then return to the background, maintaining the behavior of version 340.

**Comment by rkhrkh** [comment]
Critical UI Feedback - **System Tray Icon Missing** in Version Whispering_4.8.0_aarch64

**1. System Tray Icon Disappearance:**
   - The system tray icon is completely absent in version 4.8.0.
   - This occurs while the application is running, during dictation, and also when it's in the background.

**2. Impact on User Experience:**
   - I have no visual indication of whether the application is active or not.
   - It's unclear if I'm currently dictating or if the app is even running.

**3. Comparison to version 3.4.0:**
   - While in 4.8.0 the available audio signal for app state changes (on/off/active) is an option, I strongly prefer a visual indicator.
   
   - When activated, version 3.4.0 brings the application to the foreground. It displays an active status indicator. This provides a clear visual confirmation that the application is operational.

**4. Current Workaround:**
   - Despite the numerous additional features in version 4.8.0 (including the ability to work with the groq API), I've reverted to using version 3.4.0  due to this issue.

I appreciate the enhancements made in version 4.8.0, but the loss of this critical UI element significantly impacts the usability for long-time users like myself.

**Comment by braden-w** [comment]
Thanks for the feedback @rkhrkh and bringing it to my attention in the discussion! Will work on a fix.

I added a new feature in #268 which enables a setting to bring the app to the foreground when recording. Will include it in my next release!

Will take a look at the Tray issue next, it's a Tauri/Rust specific issue so might require some more engineering 🧠

**Comment by rkhrkh** [comment]
Whispering_4.8.3_aarch64

 Everything works fine now. Thank you so much for the elegant solution.

**Comment by braden-w** [comment]
Thank you @rkhrkh !

I tried looking at the tray but don't have a solution at the moment unfortunately, it seems like this is some low-level Rust-specific code in the Tauri Framework that I'm not too knowledgeable in.

That being said, the Always On Top settings has been added and I hope this fixes your issue!

I'm going to close this for now, but please feel free to reopen if you ever mind find some resources regarding the tray!

I'm upgrading to Tauri v2 sometime in the future, which also has some [API changes to the tray extension](https://v2.tauri.app/reference/javascript/api/namespacetray/).
