### ISSUE TITLE
Can't paste or enter the API Key

### ISSUE THREAD

**Issue by larsburkhardt** [braden-w/whispering#164]
Hello,
installed the extension in Brave, Chrome and Edge - no matter where, I can't paste my API Key or enter anything in the form field.
No errors shown

**Comment by braden-w** [comment]
On it! Thank you for bringing it to my attention, it must have been broken in my last update adding password support #161 !

**Comment by braden-w** [comment]
Fixed now! Awaiting deployment to Chrome Web Store :)
