### ISSUE TITLE
V-4.6.2-BROKEN on mac M1

### ISSUE THREAD

**Issue by OLH21** [braden-w/whispering#182]
Sound recording is broken since V 4.6.2-> 
Recording is inaudible and the transcription failed of course
Both X64 and ARM version are broken

V4.6.1 is ok

**Comment by braden-w** [comment]
@OLH21 Thank you for the heads up! Looking for a hotfix asap

**Comment by braden-w** [comment]
@OLH21 found the culprint and just pushed a Hotfix! Thank you for letting me know about this bug so quickly 🙏
