### ISSUE TITLE
V-4.6.2

### ISSUE THREAD

**Issue by worldoptimizer** [braden-w/whispering#184]
I previously used a forked version of Whispering that I modified when the ChatGPT domain changed. It worked by simply searching and replacing the endpoint. However, it stopped working today, so I installed the latest version (4.6.2) from the Chrome Web Store.

I like the new tab with all my recordings (see below), although some things are different now:

1. I often encounter a white screen of death, seemingly caused by the extension modifying the DOM (using in Arc on macOS). Steps to reproduce… use a form field apart from the main input on Claude (like editing a previous answer or in the projects section).
2. When I first installed it, the icon appeared in Claude and ChatGPT interfaces directly in the input. After disabling and re-enabling the extension, these icons no longer show up.
3. I noticed that all recordings now seem to be stored on your server (https://whispering.bradenwong.com/recordings). Was this always the case? This raises concerns about GDPR compliance and privacy. I was under the impression that by using my OpenAI key, I was communicating directly with OpenAI, and your app was just providing an interface.
4. Since the update, I receive a notification after every recording to visit my dashboard. These notifications pile up and become overwhelming. Is there a way to disable them?
5. Previously, I could disable the clipboard functionality and still use the extension to transcribe. I liked this because I could keep a task-specific file in my clipboard while talking to ChatGPT or Claude, then paste the file after finishing the recording with the transcription being place in the input. Now, my clipboard is replaced by the transcription, and if I disable this functionality, the transcription doesn't appear in the chat interface anymore.

Are these changes intentional, or am I experiencing user error? I'd appreciate your feedback on these concerns and suggestions.

**Thank you for this invaluable tool that I've been using for some time now.**

**Comment by worldoptimizer** [comment]
I noticed that the extension now creates a new tab for each recording, which stays open even after pasting. There's also a recording indicator at the top of the screen in macOS (orange microphone symbol) that only goes away when I close that new tab. Before it would only show up when recording and not stay on indefinitely (until that new tab is closed)

I'm also finding it tricky to use the extension the way I used to. Before, I could have code in my clipboard, chat with Claude, and then paste my code. Now it seems the clipboard integration is mandatory, which has thrown off my rhythm a bit making wishing the old simpler version back or a simpler way of using the current version.

On another note, I was thinking about trying out the desktop app, but I noticed it's not verified. I wonder if that's related to the costs of going through Apple's verification process? Just thought I'd mention it in case it's something you're looking into, or we could collect funds for.

I really appreciate all the work you've put into this tool - it's been invaluable for me. I'm just hoping to understand these recent changes better and see if there might be ways to tweak things to help users like me who've gotten used to certain workflows. Any insights you could share would be great!

**Comment by braden-w** [comment]
Hey man, thank you again for the detailed comments and I really appreciate the kind words, you made my day! 🙏 

Sorry again for the delayed response. I have been busy this week, but you'll see me periodically address each of your points as I make progress towards them!

**Comment by braden-w** [comment]
> * I noticed that all recordings now seem to be stored on your server (https://whispering.bradenwong.com/recordings). Was this always the case? This raises concerns about GDPR compliance and privacy. I was under the impression that by using my OpenAI key, I was communicating directly with OpenAI, and your app was just providing an interface.

Just to respond to this one right off the bat—I don't store any recordings on any servers, and I'm still committed to keeping things local.

All recordings are stored locally on your device using IndexedDb. You can see the source code for this here:

- [The recordings page which accesses the database](https://github.com/braden-w/whispering/blob/main/apps/app/src/routes/(config)/recordings/%2Bpage.svelte)
- [The database implementation](https://github.com/braden-w/whispering/blob/main/apps/app/src/lib/services/RecordingDbServiceIndexedDbLive.svelte.ts)
- [The database service definition](https://github.com/braden-w/whispering/blob/main/apps/app/src/lib/services/RecordingDbService.ts)

**Comment by braden-w** [comment]
Gonna close this thread as I'll now address each of them in #200, #201, #202, #203, and #204!

**Comment by worldoptimizer** [comment]
Thanks, I should have peeked into the code. So true... Thanks for the clarification. It might be a great point to communicate security and privacy more prominently in the UI as it's a crucial aspect (besides OpenAI handling the transcriptions, things are local).
Anytime you use the Whisper interface, you do an amazing job, and it keeps improving! Education is a priority, so no need to apologize for not responding quickly enough. It's totally fine, especially considering the open-source nature. 

# I encourage anyone reading this to also join as a sponsor!
