### ISSUE TITLE
[FEATURE REQUEST]: Integration of Whispering browser extension with Poe.com

### ISSUE THREAD

**Issue by Arche151** [braden-w/whispering#193]
@braden-w First of all thanks so much for the rapid Whispering updates! The Claude.ai integration is awesome!

Could we get Whispering to work with Poe.com? It's become my go-to for ChatGPT, Claude, and other AI models and made me cancel my ChatGPT subscription. 

I know it's more coding, but it could bring in Poe users and make Whispering even more versatile.

Appreciate your consideration and all the effort you're putting into this project.

Cheers!

**Comment by braden-w** [comment]
Just merged in a new PR for poe support! Should be releasing soon 🙂

**Comment by Arche151** [comment]
Damn, that was fast. You rock!
