### ISSUE TITLE
feat: Close to Tray

### ISSUE THREAD

**Issue by braden-w** [braden-w/whispering#199]
```
          So glad that you're back and pushing a lot of updates!
```

If I may kindly remind of the [close-to-tray feature of a fork of Whispering](https://github.com/braden-w/whispering/issues/69#issuecomment-1878164834), it would be very useful if Whispering could be minimized to the tray instead of exiting when the close button is clicked.

I believe, especially with the latest update that includes the two feedback sounds and the red recording icon in the tray, there's no longer a need to keep Whispering open as a window, and even less so in the foreground.

\_Originally posted by @DavidGP in [https://github.com/braden-w/whispering/issues/103#issuecomment-2198649557\_](https://github.com/braden-w/whispering/issues/103#issuecomment-2198649557\_)

**Comment by musaAmir** [comment]
Any update on this @braden-w? Very crucial feature for  me, and reason why I use the mainly use the extension even though I would prefer to use the desktop app, I would really like to see an option for this.
