### ISSUE TITLE
Option to turn off faster re-recording behavior

### ISSUE THREAD

**Issue by Wizek** [braden-w/whispering#251]
There is this feature:

> About recording sessions
> Faster re-recording explained
> Whispering keeps the media stream open after you start recording, enabling quick re-recording with reduced latency.
> 
> This means your computer will show this tab is still using the microphone.
> 
> When finished, click the 🔴 button to close the stream and end microphone access.

I appreciate the motivation behind this, and this might be very useful for lots of people, I however have not noticed a large latency to begin with, and having a recording tab in the background has given me pause a few times when I noticed it later. So I'd like an option to turn this off.

Some alternative ideas in case the above sounds sub optimal for some reason:

1. Quick timeout for the recording tab, maybe settable in seconds, after a recording ends.
2. Option to work similarly as Whisler for ChatGPT, i.e. do the recording on the same tab as the icon was clicked. This has some trade-offs too.

**Comment by braden-w** [comment]
Love this feature idea and also was independently was thinking of incorporating it in the next release! Knowing that community members will make it a higher priority. Thank you for letting me know and hope to merge soon!

**Comment by Wizek** [comment]
@braden-w Glad to hear! Out of curiosity, you are referring to the main idea, i.e. option to turn off re-recording, right? Or one of the alternative ideas?

**Comment by AlpSantoGlobalMomentumLLC** [comment]
I to add something as brainstorming idea: Another option would be to having a pleasant sound after a time. For example avery 20 
 seconds. That I'm capable to make longer dictations and also if I started accidentally, I get a reminder to turn it off. Instead to decide to limit my dictation time,  Up front..
