### ISSUE TITLE
Getting many notifications and errors in Arc

### ISSUE THREAD

**Issue by worldoptimizer** [braden-w/whispering#255]
![CleanShot 2024-08-07 at 10 23 55@2x](https://github.com/user-attachments/assets/241a22e5-5a13-459d-808a-e49ea5d11b6c)

used in claude.ai
---

Errors Encountered:
Error: Unable to copy transcribed text
Details: navigator.clipboard.writeTextToCursor is not a function

---

Error: Failed to play sound stop
Details: Failed to play sound stop in active tab 1048683558
Error: Failed to play sound start
Details: Failed to play sound start in active tab 1048683558

**Comment by braden-w** [comment]
Referenced in #256, also working on a hotfix for unable to copy transcribed text error!
