### ISSUE TITLE
Bug: Chrome Extension: Unable to copy transcribed text to clipboard in active tab

### ISSUE THREAD

**Issue by Wstnn** [braden-w/whispering#256]
" navigator.clipboard.writeTextToCursor is not a function "

Happens whenever i end a transcript. i get the content in the small text output window but automatic pasting isnt working.

Chrome
Version 127.0.6533.89

**Comment by braden-w** [comment]
Pushing a hotfix asap. This bug was addressed in a previous commit but somehow wasn't merged. Sorry for the inconvenience!
