### ISSUE TITLE
Trojan:Win32/Bearfoos.A!ml / Trojan.Win64.Crypt 

### ISSUE THREAD

**Issue by AlpSantoGlobalMomentumLLC** [braden-w/whispering#273]
Hello,
windows Defender deletes the file with the reason Trojan:Win32/Bearfoos.A!ml

Virus Total says "google" detect Trojan.Win64.Crypt
https://www.virustotal.com/gui/file/25be7abf46b70cc00d41a6e6f88abc07b3c55925244c622789e51aa87ee3d1f8/detection/f-25be7abf46b70cc00d41a6e6f88abc07b3c55925244c622789e51aa87ee3d1f8-1723035681

Trojan.Win64.Crypt | IKARUS | Aug 5, 2024
https://metadefender.opswat.com/results/file/bzI0MDgwOXQtOVJFOU0wdVZmYzRkSWI4dlc_mdaas/regular/multiscan

**Comment by braden-w** [comment]
Hey @AlpSantoGlobalMomentumLLC !

Thanks for bringing this to my attention! Unfortunately, I don't really know how to best diagnose this issue as I don't have a Windows computer, and all of my build is automated with the Tauri framework. Hopefully, this is a benign error that just happens with the build step as Tauri is a pretty trustworthy open-source framework. Do you have any other extra information that might be helpful for this issue for me to debug it?

I'm going to mark this as closed for now, but if you have any more information feel free to reopen it and I'll take a look!

Thank you again for your help!

**Comment by AlpSantoGlobalMomentumLLC** [comment]
I don't have any extra information. But the first idea would be to submit by Microsoft, Google and IKARUS  a false positive.  Usually they have forms for something like this, even they are sometimes a little bit hidden.
