### ISSUE TITLE
hotfix: Frame with ID 0 was removed

### ISSUE THREAD

**Issue by worldoptimizer** [braden-w/whispering#277]
![CleanShot 2024-08-10 at 14 22 55@2x](https://github.com/user-attachments/assets/880e15d0-8ae9-4924-bde4-29ddcdfae565)

I am really missing the old version by now. It always work and was straightforward.

**Comment by worldoptimizer** [comment]
I switched to the application version as the Chrome extension has been too faulty for me in recent weeks.

**Comment by worldoptimizer** [comment]
https://github.com/user-attachments/assets/3b658743-c8f2-4bc5-b393-11807a924c62

All the notifications completely obscure the actual interface, preventing me from clicking anything behind them until they disappear. I don't need a notification that something is in my clipboard if I just clicked the clipboard icon. I'm really not to keen of these notifications, as I don't see any benefit from them apart from possibly indicating errors. The rest becomes clear after using the app a couple of times (like finding old recordings, etc.). I hope that feedback makes sense.

**Comment by worldoptimizer** [comment]
I finally found the reason for the yellow indicator. When you record, a red dot appears, and when you hover over it (DON'T CLICK), a tooltip appears. Carefully navigate to the tooltip and hover over what it is (an underline appears) and click on that. Then, you will find the explanation.

Now that I have read and understood that it keeps a line open, I suggest making this an option under settings, as I don't want it to be the default. I don't mind the small delay to connect and disconnect.

A password field type for the OpenAI key would be great, as it is currently exposed when the preferences are opened in a stream.

**Comment by braden-w** [comment]
Hey @worldoptimizer , thank you for bringing these issues to my attention! I really appreciate it and the feedback.

I'm working on a hotfix for the extension. I'm not sure why it suddenly broke, and it might be something to do with a recent update with the underlying framework, Plasmo.

As for the recording feature and the microphone on the desktop app, that's going to be fixed in the next release as there already has been a fixed in #251 .

I'm also going to reinstate that password field like you said! Follow it in #278

**Comment by braden-w** [comment]
Just released a new version that addresses most of the points that we've discussed above. The final hotfix I'm working on is the extension as it's currently broken. I'm working as quickly as possible to get a new architecture for it up!

**Comment by braden-w** [comment]
I just merged in a new pull request and update to the extension that makes communication much more robust and should fix all the issues with frames from before. Sorry about that!
