### ISSUE TITLE
Automatic paste doesn't work on recent versions (MacBook M1)

### ISSUE THREAD

**Issue by Moaness** [braden-w/whispering#284]
Hi till a few versions ago (I think v4.6.3) the automatic paste function was working fine. Now it's a hit and miss. I had to disable then re-enable accessibility permission to work- now it doesn't work still. The dictated text is available on Whispering and on manual paste but doesn't happen automatically for some reason. Any solutions? (I'm using MacOS Sonoma)

**Comment by rkhrkh** [comment]
It works with my MacBook M1 Pro macOS Sonoma. 

Look at the installation instructions. Simply disabling and re-enabling accessibility permission won't work; **you must first completely remove** the Whispering add-on from there and then re-add it after you have installed the new version. Then it works fine.

**Comment by braden-w** [comment]
@Moaness Just checked and great catch! This seems to be a really strange bug where paste doesn't work whenever the app goes into the background, so the "When Recording" settings unintentionally blocks paste since the app is going back into the background before pasting.

As a temporary fix, set "Always on Top" to "Always". Will work on some sort of fix!

**Comment by Moaness** [comment]
Thanks I realised too that keeping it in the foreground makes it work. Hope to see it fixed in an upcoming update. Keep up the good work!

**Comment by Moaness** [comment]
Talking about this, I found myself using the app in minimised version when keeping it on top. Could there be a future version where app is persistently in a floating mode (after launching) possibly with only the dictation button and another settings button?

**Comment by braden-w** [comment]
@Moaness, the paste after transcription functionality should be working now even when the Windows only on top of the court! So sorry for the delay on the release.

https://github.com/braden-w/whispering/releases/tag/v5.1.0

I'll be marking it as an official in just a bit.

**Comment by braden-w** [comment]
> Talking about this, I found myself using the app in minimised version when keeping it on top. Could there be a future version where app is persistently in a floating mode (after launching) possibly with only the dictation button and another settings button?

Going to address this in the future with #334 ! Thank you for the suggestion.

Will be closing now, but feel free to open a new issue if issues persist!
