### ISSUE TITLE
Windows 10 - Whispering 5.0.0 Unresponsive When Cursor Outside Application

### ISSUE THREAD

**Issue by rkhrkh** [braden-w/whispering#316]
The application does not respond on Windows 10 when the cursor is outside the application.

I wanted to install the current version of Whispering 5.0.0 on a friend's laptop. Everything works, but **when the cursor is within another application**, Whispering no longer responds. I have tried all possible keyboard shortcuts to activate Whispering. Whispering does not react.

After installing the old version of **Whispering 3.4.0, everything works normally.**

**Info**

**Device Specifications**

* HP Spectre x360 Convertible 15-bl0XX
* Device name: DESKTOP-RHJ1HV7
* Processor: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz 2.90 GHz
* Installed RAM: 16.0 GB (15.9 GB usable)
* System type: 64-bit operating system, x64-based processor
* Pen and touch: Support for pen and touch input with 10 touch points

**Windows Specifications**

* Edition: Windows 10 Home
* Version: 22H2
* Installed on: 09/2024
* OS build: 19045.4894
* Performance: Windows Feature Experience Pack 1000.19060.1000.0

**Comment by DavidGP** [comment]
v.5 works for me, both in Windows 10 and 11. Are you sure that you have the hotkey syntax correct?

**Comment by rkhrkh** [comment]
Here's the English translation of your message:

I didn't know that the hotkey syntax only accepts uppercase letters, as I only use lowercase letter combinations on macOS. 

**Does this mean** I have to press e.g.  "String" and "Shift" and then the desired letter? I can only try it out the next time I meet my friend with his laptop.

**Comment by DavidGP** [comment]
No, but I believe you must enter uppercase letters into the hotkey box of Whispering. You still can use the corresponding lowercase letter when hitting the hotkey on the keyboard.

**Comment by rkhrkh** [comment]
**I had entered lowercase letters** as keyboard shortcuts, and as long as the cursor was within the application "Whispering," the shortcuts worked with the lowercase letters. However, there was no response from Whispering once the cursor was outside the application and in a different one. 

In any case, I will try again using uppercase letters as keyboard shortcuts.

**Comment by braden-w** [comment]
@rkhrkh Hopefully this should work now in the latest release!

I've been ironing out the kinks of Tauri's new shortcut manager, but it should solve a whole host of issues. The old shortcut manager had a lot of issues where it wouldn't fire when the window wasn't in focus. The latest manager seems to have fixed this problem. Could you let me know? If this issue still persists, could you create a new issue?
