### ISSUE TITLE
Multiple application icons are shown in the system tray.

### ISSUE THREAD

**Issue by beefontoast** [braden-w/whispering#351]
When using the application and opening it only one time, there are multiple icons that are shown in the system tray. 
![image](https://github.com/user-attachments/assets/6e604851-e027-4ec7-9251-8da6fc32ff8d)

**Comment by beefontoast** [comment]
Closing as this is listed in another active thread.

**Comment by homelab-00** [comment]
> Closing as this is listed in another active thread.

Do you mind linking the thread?
