### ISSUE TITLE
5.1.2

### ISSUE THREAD

**Issue by hi4nik** [braden-w/whispering#356]
3 microphone icons in the tray, windows 11.
![Screenshot_1](https://github.com/user-attachments/assets/e9ebe462-45ee-4a81-9f2e-1e838f073176)

**Comment by rkhrkh** [comment]
This is a known issue, same here.

**Comment by Arche151** [comment]
same issue

**Comment by DavidGP** [comment]
Still seeing the issue in version 5.1.2.

**Comment by braden-w** [comment]
Hopefully fixed in [this commit](https://github.com/braden-w/whispering/commit/6f2df0f52878bbef68ad70dd984319915f4c3762)! Added a check to ensure we aren't recreating the trayIcon. Will be released in `5.2.1`.

**Comment by braden-w** [comment]
Should be closed in #403 !
