### ISSUE TITLE
Continues to record in chat.openai.com

### ISSUE THREAD

**Issue by grassick** [braden-w/whispering#49]
When I click on the microphone in Chrome in chat.openai.com, it continues to process audio after clicking stop. That is, the red dot is still present in the Chrome tab and the task manager reports that audio is being processed. 

The audio is processed normally and the transcript is created after clicking stop. The problem is that the audio subsystem is still engaged.

**Comment by Arche151** [comment]
I have the exact same problem!

**Comment by braden-w** [comment]
Hey guys, sorry for the late response-was out of the house! I've also had a similar issue in the past, and will take a look into it! Will try to fix this by the next release.

**Comment by Arche151** [comment]
No worries and thank you so much!

**Comment by braden-w** [comment]
Hey all, this should now be fixed in the latest PR #50 and is pending approval in the Chrome store! Hopefully update comes soon :)
