### ISSUE TITLE
Browser extension and app not working.

### ISSUE THREAD

**Issue by swimJim** [braden-w/whispering#53]
Both the app and the extension are not currently working for me because of some kind of API error. However, other services I use that rely on the OpenAI API for whisper transcription are working correctly. I am not sure what the problem is but I thought I would report it to you.

**Comment by swimJim** [comment]
Both seem to have started working again.

**Comment by braden-w** [comment]
Hey @swimJim, thanks for bringing this up!

I know you closed this earlier but just wanted to respond that I agree! I've taken a look into the issue and oddly enough, I encountered the same problem when I initially tried to debug it. However, after waiting for a bit, the issue seemed to resolve itself. I suspect it could be an issue with OpenAI's Whisper API, possibly a temporary hangup or crash. That falls outside the jurisdiction of Whispering but definitely important to note.

**Comment by swimJim** [comment]
It started to work again.

**Comment by braden-w** [comment]
Awesome, great to hear!

I hope to dedicate a few days on fixing up the app sometime by next month.
Scheduling has been tough but would like to look into what’s going on.

**Comment by DavidGP** [comment]
I am also seeing again that the browser extension is not working at all 😥

**Comment by braden-w** [comment]
Going to close this now that the latest releases have addressed desktop concerns. Am working on bug fixes for the latest extension update too. Thank you guys!!
