### ISSUE TITLE
[Suggestion] Tick box in order to 'Auto-translate transcription to English'

### ISSUE THREAD

**Issue by Detet** [braden-w/whispering#55]
Hey this is not really an "issue" more of a suggestion/request for a feature! The idea of a tick box is just a suggestion on how to implement it.

Other services I have been using that uses openai-whisper (only on a website not as an extension or app) have had both the "transcribe" and "translate" available. The translate automatically translate spoken language to English.
![image](https://github.com/braden-w/whispering/assets/121098786/e56ab087-fab3-432e-926c-b39b2945fb85)

I think the reason for why this feature is desirable is evident. It would allow people who are not very well versed in the English language to easier communicate things they aren't really sure on how to say in English in their own language, and then easily send it.

This would be so appreciated by many (including me) I think!

Thank you for this software!

**Comment by Arche151** [comment]
The development of Whispering seems to be dead :( I have been in touch with the developer 2 months ago. Since then I can't reach him anymore and the extension hasn't been updated. I hope, he's all right

**Comment by swimJim** [comment]
I spoke with the developer a couple of weeks ago. He says he's still looking to add features to the project; it's just that he's gotten busy with school lately, I think. Hopefully, more updates will be forthcoming soon. Quick question: Are the Whispering app or extensions working for anyone? They seem to be down for me right now, giving an error about API keys, even though my API keys work for other apps that use the Whisper API key.

**Comment by Arche151** [comment]
Ahh okay, thanks for the info! For me, the desktop app never properly worked (MacOS) but the extension works fine in Brave (Chromium).

**Comment by braden-w** [comment]
Hey @Arche151 and @Detet , thanks for the issue! And sorry @Arche151 for being hard to reach a few months ago.

This has been closed in #81 and #125. You are now able to set language targets in the settings page!

![image](https://github.com/braden-w/whispering/assets/13159333/b9c095de-ca40-4c65-b0ca-34d37e0326a0)

**Comment by braden-w** [comment]
* I just realized that you are referring to translation, not just transcription. And so this might be a separate feature. I'll be taking a look at this later!

**Comment by Detet** [comment]
> * I just realized that you are referring to translation, not just transcription. And so this might be a separate feature. I'll be taking a look at this later!

With the new GUI, it seems to work. I just need to choose 'English' as the output language, and it will translate to English even if I speak in Swedish. It would be helpful to have a convenient way to switch between translating the text to English or not. For now, I'm delighted with the update and its numerous quality of life improvements :) Thank you for providing this technology! You're amazing!

**Comment by braden-w** [comment]
@Detet Thank you very much for the kind words, and very happy to hear that the latest version addresses this!!

> It would be helpful to have a convenient way to switch between translating the text to English or not.

Just to clarify regarding this, are we talking about a toggle just for English, located in a more accessible/global location other than settings?
