### ISSUE TITLE
Sponsor or one time donations?

### ISSUE THREAD

**Issue by cgbur** [braden-w/whispering#56]
Hi I really love this project and its become a really important part of my workflow. This is exactly what I have been looking for for such a long time and it is wonderful. 

I don't know if you plan to continue to add features or improvements, but either way I'd like to help finically and eventually with some code when I have the time. Would you consider adding a sponsorship to the repository or contact me directly to give a donation to support your work?

**Comment by doxgt** [comment]
Definitely can see myself and others onboarding this.

**Comment by braden-w** [comment]
Hey @cgbur and @doxgt! Thank you so, so much. I'm extremely touched by your interest in donating! ♥️

I just opened sponsorship and you can see my GitHub sponsorship link [here](https://github.com/sponsors/braden-w). Thank you all once again!

![CleanShot 2024-07-01 at 21 32 14@2x](https://github.com/braden-w/whispering/assets/13159333/305b2e02-a191-4e99-8d88-ba8391c7ac15)
