### ISSUE TITLE
Microphone always in use

### ISSUE THREAD

**Issue by cgbur** [braden-w/whispering#57]
Even when not actively recording it appears to be always using the microphone on my mac. It also seems to idle with 5-10% cpu usage even when not recording. Most speech to text apps I've used will release the microphone when not in use.

After the first activation, it will continually hold onto the microphone.

**Comment by braden-w** [comment]
Great point, MediaStream and MediaRecorder instances have been tidied up in #134 and as a user you should now have control of when to release the microphone by clicking the red circle to end the recording session! Thank you again!
