### ISSUE TITLE
Consider adding an auditory indication for start/stop

### ISSUE THREAD

**Issue by cgbur** [braden-w/whispering#58]
Right now it brings itself to the foreground but I have seen it not do this. Also you then must check if its in the recording state if you keep it on another window. A setting to have a subtle enable/disable chime like the iOS and Mac dictation would be nice, and also a good indication of when the microphone is in use.

**Comment by swimJim** [comment]
I ended up making a script in the programming language AutoHotKey to do just that whenever I hit the transcribe button that I assigned to my mouse. Definitely a worthy suggestion. The audio feedback is helpful. It would be particularly great if audio feedback was supported by the Whisper program itself.

**Comment by DavidGP** [comment]
There is this fantastic fork of Whispering which should at least help with this issue!
https://github.com/braden-w/whispering/issues/69

**Comment by braden-w** [comment]
Hey guys! There is now a tray icon and audio cues for start and stop. This was closed in #108 and the [latest version](https://github.com/braden-w/whispering/releases) so I will be closing now :) thank you very much!
