### ISSUE TITLE
Retry option for failed or timed out transcription requests

### ISSUE THREAD

**Issue by cgbur** [braden-w/whispering#59]
I just had a 1 minute long transcription request timeout/fail for an unknown reason. I have the audio still loaded in the app and can listen back to it, however there is no "try again" or "transcribe stored audio" button. Some way of retrying failed requests would be a nice quality of life feature.

**Comment by gabriellenz** [comment]
I have the same request. I use this every day to help with my work, it's just so amazing, but I'd say once a day or so, a 5-minute recording or 7-minute recording will fail. Huge thanks for making this, and I'm using Whispering to write this comment.

**Comment by braden-w** [comment]
Thanks for the feedback guys! I have this feature working in /dev and hope to include it in the next release, coming up in one or two weeks or so 😁 

I apologize for the delay in the responsiveness over the past few months—school has been crazy. Hope this helps!

I'll revisit this issue and reply+close it once it's addressed in our next release!

**Comment by braden-w** [comment]
Hey guys! This was closed in #108 and the latest version so I will be closing now :) thank you very much!
