### ISSUE TITLE
Option to set a specific language

### ISSUE THREAD

**Issue by lukasz-dutka** [braden-w/whispering#60]
Hi, I find the desktop version extremely useful.

When working with short sentences, the model doesn't always identify the language correctly. I speak in English, Spanish and Polish. And yet occasionally I get quite random transcription in Russian, Hebrew, Hindi or Japanese. 

It would be useful to have the option to set a specific language so as to avoid the model performing language identification and the potential errors related to that. For example, when working with speech in Spanish, I would choose the option "Spanish" to always get the transcription in this language.

**Comment by braden-w** [comment]
@lukasz-dutka Sorry for the late response, this should be addressed in the latest version, as of writing, `v4.2.1`!

You can download it here:

https://github.com/braden-w/whispering/releases

And also see it in action here:

https://whispering.bradenwong.com/settings

![CleanShot 2024-06-29 at 14 19 08](https://github.com/braden-w/whispering/assets/13159333/3e02ed1b-822f-438d-95c5-678c41465a10)
