### ISSUE TITLE
Prevent accidental recording of 2+ hour recordings

### ISSUE THREAD

**Issue by braden-w** [braden-w/whispering#69]
Some users have accidentally recorded very long recordings with the extension. Better visibility of recording status, warnings, etc. would be appreciated.

**Comment by swimJim** [comment]
Yes please. I dislike ending up with a five hour-long recording because the hotkey does not seem to trigger. It would be great if you could set a maximum length in minutes for individual recordings so that, for  instance, Whispering would automatically stop any single recording that exceeded 20 minutes or whatever time you set for individual recordings.

**Comment by HamzaETTH** [comment]
To try to prevent this, I've quickly made a fork where the program minimizes to the system tray instead of closing, and the tray icon changes to include a red circle when it's recording. You can check it out.

**Comment by MuhsinunC** [comment]
> To try to prevent this, I've quickly made a fork where the program minimizes to the system tray instead of closing, and the tray icon changes to include a red circle when it's recording. You can check it out.

I really like this idea. I think that this would be a great thing to implement into the official project. I know Discord, for example, has a little icon that lights up when it's recording your mic, and that makes it really easy to tell if your mic is muted or not.

**Comment by HamzaETTH** [comment]
> I would love to try your fork, but I'm a noob who can only run Windows executables. Do you have a happy compiled version of your fork with a notification feature?

[Here.](https://github.com/HamzaETTH/whispering/releases/tag/v3.4.1)

**Comment by swimJim** [comment]
Thank you, I just had a three hour long recording today, that I did not intend. You are my hero for saving me my pennies.

**Comment by DavidGP** [comment]
This fork is amazing and such a big improvement! It also seems to be more stable in that it no longer takes the focus away from the current window, which seemed to happen with the original version. Braden, when continuing the development of Whispering, please retain this feature and build upon this fork. Thanks all!

**Comment by swimJim** [comment]
> > I would love to try your fork, but I'm a noob who can only run Windows executables. Do you have a happy compiled version of your fork with a notification feature?
> 
> [Here.](https://github.com/HamzaETTH/whispering/releases/tag/v3.4.1)

Is there any way you could modify the fork to work with the recent API changes?

**Comment by doxgt** [comment]
Supposedly Whisper on OpenAI rejects any raw audio file > 25 MB.  WAV format that Whispering records at generates approximately 10 MB/min, even with "silence" (I didn't verify this personally).  Thus any WAV recording from Whispering over 3 min in length is unlikely to result in consumption of tokens or success of transcription, in theory anyway.

**Comment by braden-w** [comment]
Hey everyone, sorry for jumping on this thread so late—I finally have returned to development a few months later!

I added a cancel button in the 4.0.0 release #108 and it should hopefully be working in the [latest version](https://github.com/braden-w/whispering/releases) (as of writing, `v4.2.1`).

Could you guys let me know if the new implementation is missing anything, and I'll get to work? In the meantime, I'll close this issue as addressed. Reopen if issue persists. Thank you all once again!
