### ISSUE TITLE
Firefox does not go into recording

### ISSUE THREAD

**Issue by joshcho** [braden-w/whispering#71]
When clicking on the microphone button, it does not ask for permissions. Thus clicking on the microphone button does not go into the red square button. On both Mozilla Firefox 121.0 and Mozilla Firefox 122.0b3 (developer edition). The extension works fine in Chrome for me.

**Comment by braden-w** [comment]
Going to address this issue when I come around to fixing #156. Thank you again and sorry for the delay!
