### ISSUE TITLE
The uninstaller for Whispering Desktop. Mislabeled as a virus.

### ISSUE THREAD

**Issue by swimJim** [braden-w/whispering#73]
I'm pretty sure it was a false positive; I just wanted to mention it here

**Comment by OLH21** [comment]
has this one too by kasperky. is it a false pos or did the repo got hacked ?

**Comment by braden-w** [comment]
Hey guys, false positive! I unfortunately haven't had time to notarize and sign the installers.

If anyone doesn't trust me and wants to be ultra safe, you can
1. Clone the repository with `git clone https://github.com/braden-w/whispering.git` to get a redundant copy of the source code on your local machine.
2. Compile the source code on your machine into an executable.
    - Run `pnpm i` to install all dependencies before compiling
    - Run `cd apps/app` , then `pnpm tauri build` to build the executable yourself

Cheers!
