### ISSUE TITLE
Something went wrong. Please verify that your API Key in settings is correct.

### ISSUE THREAD

**Issue by VindiceCode** [braden-w/whispering#74]
Hi, I am creating an API key within OpenAI and keep getting the above error. Doesn't seeem to be any fix I can think of. Appreciate any clarity!

**Comment by swimJim** [comment]
I have the same problem that would come up when my firewall intermittently starts blocking MS WebViewer. It's not called exactly that, but it's something close.

**Comment by CognitiveTwo** [comment]
Same issue here :/ maybe a change in the OpenAI API? (maybe the new whisper model)

**Comment by punksterlabs** [comment]
Is there no way to re-try? I get this error even when the API key is there properly inputted. Now I have to download it and then reup it on some other whisper instance. Is there a way Whispering can retry?

**Comment by modjfy** [comment]
I have the same problem.

**Comment by cgbur** [comment]
There is the remaining issue of OpenAI not responding sometimes and needing to repeat your audio to send the request again. However if you are getting it every time, on February 22 OpenAI switched their pricing to use credits that are prepaid. If you have not made any changes and are getting constant failures, go to billing and set up the credits for your account and api keys.

**Comment by modjfy** [comment]
I already suspected that it could be because I didn't register any payment methods. Is there no free limit?

**Comment by cgbur** [comment]
> I already suspected that it could be because I didn't register any payment methods. Is there no free limit?

Unless you have some special deal then no I don’t believe there is a free tier. I’ll add however that whisper is incredibly cheap. I use it for probably 30 minutes of audio dictation every day and my bill is pennies.

**Comment by modjfy** [comment]
Thanks, I guess I'll have to add a payment method then. Do you happen to know of an Android keyboard that implements the Whisper API?

**Comment by punksterlabs** [comment]
> There is the remaining issue of OpenAI not responding sometimes and needing to repeat your audio to send the request again. However if you are getting it every time, on February 22 OpenAI switched their pricing to use credits that are prepaid. If you have not made any changes and are getting constant failures, go to billing and set up the credits for your account and api keys.

Currently I am forced to download the audio and run it via another transcription software. The ability to retry would fix it. I have a paid API account

**Comment by cgbur** [comment]
> > There is the remaining issue of OpenAI not responding sometimes and needing to repeat your audio to send the request again. However if you are getting it every time, on February 22 OpenAI switched their pricing to use credits that are prepaid. If you have not made any changes and are getting constant failures, go to billing and set up the credits for your account and api keys.
> 
> Currently I am forced to download the audio and run it via another transcription software. The ability to retry would fix it. I have a paid API account

Yeah a manual or automatic retry feature would fix the issue. I have not had time to contribute the changes and the repo is waiting on svelte 5 and dev to give it love. Understandable as they are in college so no blame there.

**Comment by swimJim** [comment]
Well, I was just experiencing this error today and the way I resolved it was to go into my OpenAI billing page and check the billing settings because OpenAI recently removed the simple pay-as-you-go API setup in favor of having to prepay each month. So just make sure that your balance is positive for the Whispering program to work.

**Comment by DavidAG2000** [comment]
I had the same problem and just solved it this way. I would mark this issue as solved : )

**Comment by braden-w** [comment]
Closing this issue now that it has been resolved. Thanks everyone!
