### ISSUE TITLE
Are different languages supported?

### ISSUE THREAD

**Issue by jcubic** [braden-w/whispering#87]
Does this extension work only with English? I'm not able to recognize Polish language. It records an audio that I can listen when click on the wispering icon.

**Comment by jcubic** [comment]
I'm working on language selector option. I hope you accept PR.

**Comment by braden-w** [comment]
@jcubic  Sorry for the late response, this should be addressed in the latest version, as of writing, `v4.2.1`! I was having a lot of issues with building and releases until now.

You can download it here:

https://github.com/braden-w/whispering/releases

And also see it in action here:

https://whispering.bradenwong.com/settings

![CleanShot 2024-06-29 at 14 19 08](https://github.com/braden-w/whispering/assets/13159333/3e02ed1b-822f-438d-95c5-678c41465a10)
