### ISSUE TITLE
Force transcription in one language

### ISSUE THREAD

**Issue by jralduaveuthey** [braden-w/whispering#91]
I am not a native english speaker and most of the times when I try to use it to transcribe english it returns me the correct text but in another language. This does not happen with the original chatGPT whisper button in the app or with any other service I have tested that uses Whisper.
Optimally there would be a dropdown menu to select the language, but if not at least that it works in english like other whisper -backed services. 
For me at the moment is a reason not to use the plugin unfortunately :/

**Comment by braden-w** [comment]
Thank you so much for the feedback!! Language selection is currently working in /dev and I will be including it in the release coming up next week :) I’ll reply again and close this issue once it’s merged!On Apr 13, 2024, at 5:16 AM, jralduaveuthey ***@***.***> wrote:﻿
I am not a native english speaker and most of the times when I try to use it to transcribe english it returns me the correct text but in another language. This does not happen with the original chatGPT whisper button in the app or with any other service I have tested that uses Whisper.
Optimally there would be a dropdown menu to select the language, but if not at least that it works in english like other whisper -backed services.
For me at the moment is a reason not to use the plugin unfortunately :/

**Comment by jralduaveuthey** [comment]
Awesome thanks!

**Comment by jralduaveuthey** [comment]
@braden-w do you know when the new release will be?:)

**Comment by braden-w** [comment]
@jralduaveuthey Sorry for the late response, this should be addressed in the latest version, as of writing, `v4.2.1`!

You can download it here:

https://github.com/braden-w/whispering/releases

And also see it in action here:

https://whispering.bradenwong.com/settings

![CleanShot 2024-06-29 at 14 19 08](https://github.com/braden-w/whispering/assets/13159333/3e02ed1b-822f-438d-95c5-678c41465a10)
